export const OPTION_SELECTED = "OPTION_SELECTED";
export const PREVIOUS_QUESTION = "PREVIOUS_QUESTION";
export const NEXT_QUESTION = "NEXT_QUESTION";
export const RESET_QUESTION = "RESET_QUESTION";
export const RESET_OPTION_SELECTION = "RESET_OPTION_SELECTION";
